#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WCCMobile.Resource", IsApplication=true)]

namespace WCCMobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int days_array = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int locations_array = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int meridian_array = 2131034114;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int theme_holo_light_background = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_athletics = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_blackboard = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_calendar = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_career_services = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_counseling = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_dining_services = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_directory = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_library = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_mail = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_map = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_student_involvement = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_transfer_services = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_transit = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int placeholder_128x185 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int WCCMainAppIcon_57x57 = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int BasicInfoList = 2131230720;
			
			// aapt resource value: 0x7f08001c
			public const int ImageContainer = 2131230748;
			
			// aapt resource value: 0x7f08001e
			public const int PhoneBookList = 2131230750;
			
			// aapt resource value: 0x7f08001d
			public const int SubAppContainer = 2131230749;
			
			// aapt resource value: 0x7f08000a
			public const int bldgLabel = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int bldgSpinner = 2131230731;
			
			// aapt resource value: 0x7f080006
			public const int courseLabel = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int courseName = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int courseSpinner = 2131230727;
			
			// aapt resource value: 0x7f080011
			public const int dayLabel = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int daySpinner = 2131230738;
			
			// aapt resource value: 0x7f08001b
			public const int delCourse = 2131230747;
			
			// aapt resource value: 0x7f080010
			public const int delDay = 2131230736;
			
			// aapt resource value: 0x7f080017
			public const int endTime = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int endTimeLabel = 2131230742;
			
			// aapt resource value: 0x7f080008
			public const int idLabel = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int idSpinner = 2131230729;
			
			// aapt resource value: 0x7f080001
			public const int linearLayout1 = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int linearLayout2 = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int linearLayout3 = 2131230724;
			
			// aapt resource value: 0x7f080015
			public const int merSpinner1 = 2131230741;
			
			// aapt resource value: 0x7f080018
			public const int merSpinner2 = 2131230744;
			
			// aapt resource value: 0x7f08001a
			public const int openCourse = 2131230746;
			
			// aapt resource value: 0x7f08000f
			public const int openDay = 2131230735;
			
			// aapt resource value: 0x7f08000c
			public const int roomLabel = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int roomText = 2131230733;
			
			// aapt resource value: 0x7f080019
			public const int saveCourse = 2131230745;
			
			// aapt resource value: 0x7f08000e
			public const int saveDay = 2131230734;
			
			// aapt resource value: 0x7f080002
			public const int scrollView1 = 2131230722;
			
			// aapt resource value: 0x7f080014
			public const int startTime = 2131230740;
			
			// aapt resource value: 0x7f080013
			public const int startTimeLabel = 2131230739;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BasicInfoLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CourseLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PhoneBookLayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int DiningServices = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int days_prompt = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Custom = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
