#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WCCMobile.Resource", IsApplication=true)]

namespace WCCMobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_holo_light_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_athletics = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_blackboard = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_calendar = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_career_services = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_counseling = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_dining_services = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_directory = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_library = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_mail = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_map = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_student_involvement = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_transfer_services = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_transit = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int placeholder_128x185 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int WCCMainAppIcon_57x57 = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int BasicInfoList = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int ImageContainer = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int PhoneBookList = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int SubAppContainer = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout1 = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BasicInfoLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PhoneBookLayout = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int DiningServices = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
